import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type AppLang = 'ku' | 'en' | 'ar';

type LanguageContextValue = {
  lang: AppLang;
  isRTL: boolean;
  setLang: (lang: AppLang) => Promise<void>;
  t: (key: string) => string;
};

const translations: Record<AppLang, Record<string, string>> = {
  en: {
    app_name: 'Walam',
    intro_subtitle: 'Manage pages and automate replies from mobile',
    use_cases: 'Usage',
    pricing: 'Pricing',
    whatsapp: 'WhatsApp',
    website: 'Website',
    platform: 'Platform',
    login_facebook: 'Login With Facebook',
    enter_app: 'Enter',
    language: 'Language',
    home: 'Home',
    inbox: 'Inbox',
    stats: 'Stats',
    posts: 'Posts',
    chat_flow: 'Chat Flow',
    settings: 'Settings',
    dashboard: 'Dashboard',
    overview: 'Overview and key activity',
    account_time: 'Account time',
    no_expiry_date: 'No expiry date',
    time_left_suffix: 'left',
    time_passed_suffix: 'passed',
    could_not_load_dashboard_data: 'Could not load dashboard data',
    active_posts: 'Active posts',
    today_replies: 'Today replies',
    total_replies: 'Total replies',
    refresh_data: 'Refresh data',
    account_support: 'Account and support',
    help: 'Help',
    buy_plan: 'Buy Plan',
    page_stats_title: 'Pages',
    page_stats_subtitle: 'Selected page stats',
    posts_manage_title: 'Posts',
    posts_manage_subtitle: 'Active posts by selected page',
    chat_flow_subtitle: 'Messenger chat flow setup',
    total_pages: 'Total Pages',
    active_pages: 'Active Pages',
    page_stats: 'Page Stats',
    chart_last_30_days: 'Last 30 Days Chart',
    total: 'Total',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    chat_preview: 'Chat Preview',
    button_setup: 'Button Setup',
    step_by_step_buttons: 'Step-by-step Buttons',
    inbox_title: 'Inbox',
    inbox_subtitle: 'Important messages from admin',
    no_messages_yet: 'No messages yet.',
    unread_messages: 'unread messages',
    unread_message: 'unread message',
    new_message: 'New message',
    delete_message: 'Delete message',
    delete_message_confirm: 'Are you sure you want to delete this message?',
    cancel: 'Cancel',
    delete: 'Delete',
    error: 'Error',
    failed_load_inbox: 'Failed to load inbox',
    failed_delete_message: 'Failed to delete message',
    spam_tester_title: 'Spam Tester',
    spam_tester_subtitle: 'Test a comment before enabling the filter',
    comment_text: 'Comment text',
    write_comment: 'Write a comment...',
    test: 'Test',
    text_required: 'Text required',
    enter_comment_first: 'Please enter a comment first.',
    spam_test_failed: 'Could not run spam test',
    spam: 'Spam',
    safe: 'Safe',
    confidence: 'Confidence',
    detected_keywords: 'Detected keywords',
    none: 'None',
    login_failed: 'Login failed',
    dashboard_open_failed: 'Dashboard open failed',
    unknown_error: 'Unknown error',
    please_wait: 'Please wait...',
    continue: 'Continue',
    network_error_try_again: 'Network error. Please try again.',
    api_not_configured: 'API URL is not configured.',
    status: 'Status',
    expiry: 'Expiry',
    role: 'Role',
    active: 'Active',
    inactive: 'Inactive',
    admin: 'Admin',
    user: 'User',
    log_out: 'Log Out',
    log_out_confirm: 'Are you sure?',
    loading: 'Loading...',
    delete_account: 'Delete Account',
    delete_account_title: 'Delete account',
    delete_account_confirm: 'This will disable your account.',
    deleting: 'Deleting...',
    select_page: 'Select page',
    page_id: 'Page ID',
    likes: 'Likes',
    followers: 'Followers',
    replies: 'Replies',
    stats_load_failed: 'Stats load failed',
    stats_fetch_error: 'Error loading stats',
    pages_load_failed: 'Failed to load pages',
    selected_page: 'Selected page',
    change_page_hint: 'Tap page name above to change page.',
    no_pages_found: 'No pages found.',
    no_pages_available: 'No pages available.',
    no_connected_pages: 'No connected pages found.',
    blocked_page_message: 'This page is blocked and cannot be used.',
    restriction_reason_label: 'Restriction reason',
    restriction_reason_empty: 'No reason was provided.',
    blocked_account_message: 'Your account is currently restricted or deactivated.',
    select_page_first_for_posts: 'Please select a page first to view automations.',
    active_post: 'Active Post',
    active_posts_only: 'Active posts',
    all_posts: 'All posts',
    no_active_posts_found: 'No active posts found for this page.',
    inactive_post: 'Not Active',
    post_info: 'Post info',
    read_more: 'Read more',
    show_less: 'Show less',
    date: 'Date',
    set_auto_reply: 'Set Auto Reply',
    post_not_configured: 'This post has no config yet. Create one using the button.',
    load_more: 'Load More',
    refreshing_text: 'Refreshing...',
    refresh: 'Refresh',
    select_platform_page: 'Select an account/page for this platform',
    select_instagram_id: 'Select this Instagram ID',
    select_page_id: 'Select this Page ID',
    auto_reply_settings: 'Auto reply settings',
    comment_reply_message: 'Comment reply message',
    quick_comment_replies: 'Quick replies',
    quick_reply_1: 'Thanks for your comment',
    quick_reply_2: 'Please send us a private message',
    quick_reply_3: 'More details are available in inbox',
    quick_reply_4: 'Our team will contact you soon',
    quick_reply_5: 'Thank you for your support',
    quick_reply_tokens: 'Placeholders',
    quick_reply_help_short: 'Tip: use placeholders like {comment}, {user_first_name}, {page_name}, {post_id}.',
    quick_reply_custom_placeholder: 'Type your own quick reply...',
    quick_reply_add_hint: 'Tap + to add your own favorite reply',
    pm_reply_message: 'Private message reply',
    messenger_media: 'Messenger Media',
    media_types: 'Image, video, audio, buttons',
    open: 'Open',
    close: 'Close',
    image: 'Image',
    video: 'Video',
    audio: 'Audio',
    no_image: 'No image selected',
    no_video: 'No video selected',
    no_audio: 'No audio selected',
    upload: 'Upload',
    record: 'Record',
    stop_and_save: 'Stop & Save',
    delete_item: 'Delete',
    buttons_messenger: 'Messenger Buttons',
    add_button: 'Add Button',
    button_suggestions: 'Suggested buttons',
    edit: 'Edit',
    save_edit: 'Save Edit',
    save: 'Save',
    saving: 'Saving...',
    no_buttons_yet: 'No buttons yet',
    button_name_placeholder: 'Button label',
    whatsapp_phone_placeholder: 'WhatsApp number 964 xxxx xxx xxx',
    whatsapp_text_placeholder: 'Prepared WhatsApp text',
    button_link_placeholder: 'Button link (https://...)',
    enter_page_id: 'Enter Page ID',
    enter_instagram_id: 'Enter Instagram ID',
    upload_progress: 'Upload progress',
    loading_preview_audio: 'Loading audio preview...',
    cant_show_video_preview: 'Cannot show video preview.',
    cant_play_audio: 'Cannot play audio preview.',
    warning: 'Warning',
    only_images_limit: 'You can upload only {count} image(s).',
    gallery_permission_required: 'Gallery permission is required.',
    unsupported_audio_format: 'Unsupported audio format. Use mp3/m4a/wav.',
    upload_failed: 'Upload failed.',
    mic_permission_required: 'Microphone permission is required.',
    min_recording_warning: 'Please record at least 1 second.',
    button_name_required: 'Please enter button label.',
    whatsapp_phone_invalid: 'Please enter a valid WhatsApp number.',
    invalid_link: 'Please enter a valid link.',
    max_buttons_reached: 'Limit reached: only {count} buttons.',
    messenger_chat_flow_title: 'Messenger Chat Flow',
    messenger_chat_flow_sub: 'Setup buttons and automatic replies',
    page_selection: 'Page Selection',
    welcome_message: 'Welcome Message',
    welcome_placeholder: 'Welcome text for first chat',
    preview: 'Preview',
    button_name: 'Button Name',
    button_reply: 'Button Reply',
    add_button_label: 'Add Button',
    limit: 'Limit',
    link_step_to_main: 'Link step-by-step to a main button',
    main_button_name: 'Main Button Name',
    add_sub_button: 'Add Sub Button',
    sub_button_name: 'Sub Button Name',
    sub_button_reply: 'Sub Button Reply',
    save_chat_flow: 'Save Chat Flow',
    back: 'Back',
    no_text: '...',
    help_about_app: 'About App',
    help_auto_reply: 'How to set Auto Reply?',
    help_chat_flow: 'How to setup Chat Flow?',
    live_chat_whatsapp: 'Live Chat WhatsApp',
    website_label: 'Website',
    about_label: 'About',
    live_chat: 'Live Chat',
    walam_team: 'Walam Team',
    active_now: 'Active now',
    no_messages: 'No messages.',
    send: 'Send',
    write_message: 'Write message...',
    you: 'You',
    plan_monthly_price: '6.99$ / month',
    plan_quarterly_price: '17.97$ / 3 months',
    plan_yearly_price: '59.88$ / year',
    plan_basic: 'Basic',
    plan_popular: 'Popular',
    plan_best_value: 'Best Value',
    plan_start_now: 'Start now',
    plan_save_more: 'Save more with 3 months',
    plan_full_access: 'Full access for 1 year',
    plan_monthly_feature_1: 'Auto replies for Facebook & Instagram',
    plan_monthly_feature_2: 'Messenger buttons and media tools',
    plan_monthly_feature_3: 'Live chat and referral features',
    plan_quarterly_feature_1: 'Everything in Monthly plan',
    plan_quarterly_feature_2: 'Better value for 3-month usage',
    plan_quarterly_feature_3: 'Priority stability and updates',
    plan_yearly_feature_1: 'Everything in Quarterly plan',
    plan_yearly_feature_2: 'Best yearly price',
    plan_yearly_feature_3: 'Long-term growth without interruptions',
    referral_code_title: 'Referral Code',
    referral_wallet_title: 'Referral Wallet',
    referral_loading: 'Loading...',
    referral_balance: 'Balance',
    referral_pending_reward: 'Pending Reward',
    referral_earned: 'Earned',
    referral_used: 'Used',
    referral_pending_users: 'Pending users',
    referral_approved_users: 'Approved users',
    referral_used_code: 'Used code',
    referral_my_code: 'My code',
    referral_use_code: 'Use referral code',
    referral_copy_hint: 'Tap the code field then copy it.',
    referral_code_required: 'Referral code is required.',
    referral_code_applied: 'Referral code applied.',
    referral_code_copied: 'Referral code copied.',
    referral_api_not_updated: 'Server API is not updated yet. Please deploy the latest mobile-api.php.',
    apply: 'Apply',
    used: 'Used',
    copy_code: 'Copy code',
    help_about_line_1: 'This app automates replies for Facebook and Instagram.',
    help_about_line_2: 'Main benefit: faster replies, less manual time, organized conversations.',
    help_auto_1: '1) In Posts, select your page.',
    help_auto_2: '2) For each post, write Comment or PM reply.',
    help_auto_3: '3) Add media when needed (image/video/audio).',
    help_auto_4: '4) Always save after editing.',
    help_flow_1: '1) In Chat Flow, select a page.',
    help_flow_2: '2) Create main buttons (pricing, contact, tutorials...).',
    help_flow_3: '3) Set a reply text for each button.',
    help_flow_4: '4) Add step-by-step sub-buttons for deeper flows.',
    help_flow_5: '5) Preview, then save.',
  },
  ku: {
    app_name: 'Walam',
    intro_subtitle: 'بەڕێوەبردنی پەیج و ئۆتۆماتیککردنی وەڵام لە مۆبایل',
    use_cases: 'بەکارهێنان',
    pricing: 'نرخ',
    whatsapp: 'واتساپ',
    website: 'وێبسایت',
    platform: 'پلاتفۆرم',
    login_facebook: 'چوونە ژوورەوە بە فەیسبووک',
    enter_app: 'چوونە ژوورەوە',
    language: 'زمان',
    home: 'سەرەکی',
    inbox: 'نامەکان',
    stats: 'ئامار',
    posts: 'پۆست',
    chat_flow: 'چات فلۆو',
    settings: 'ڕێکخستن',
    dashboard: 'داشبۆرد',
    overview: 'پێشبینینی گشتی',
    account_time: 'کاتی هەژمار',
    no_expiry_date: 'بەرواری بەسەرچوون نییە',
    time_left_suffix: 'ماوە',
    time_passed_suffix: 'تێپەڕیوە',
    could_not_load_dashboard_data: 'نەتوانرا داتای داشبۆرد بهێندرێت',
    active_posts: 'پۆستە چالاکەکان',
    today_replies: 'وەڵامەکانی ئەمڕۆ',
    total_replies: 'کۆی گشتی وەڵامەکان',
    refresh_data: 'نوێکردنەوەی داتا',
    account_support: 'زانیاری هەژمار و یارمەتی',
    help: 'یارمەتی',
    buy_plan: 'کڕینی پلان',
    page_stats_title: 'پەیجەکان',
    page_stats_subtitle: 'ئاماری پەیجی هەڵبژێردراو',
    posts_manage_title: 'پۆستەکان',
    posts_manage_subtitle: 'پۆستە چالاکەکان بەپێی پەیجی هەڵبژێردراو',
    chat_flow_subtitle: 'ڕێکخستنی چاتی مەسنجەر',
    total_pages: 'کۆی پەیجەکان',
    active_pages: 'پەیجی چالاک',
    page_stats: 'ئاماری پەیج',
    chart_last_30_days: 'چارتی 30 ڕۆژی دوا',
    total: 'گشتی',
    daily: 'ڕۆژانە',
    weekly: 'حەفتانە',
    monthly: 'مانگانە',
    chat_preview: 'پێشبینینی چات',
    button_setup: 'ڕێکخستنی دوگمەکان',
    step_by_step_buttons: 'دوگمەی هەنگاو بە هەنگاو',
    inbox_title: 'نامەکان',
    inbox_subtitle: 'نامە گرنگەکانی ئەدمین',
    no_messages_yet: 'هێشتا هیچ نامەیەک نییە.',
    unread_messages: 'نامەی نەخوێندراو',
    unread_message: 'نامەی نەخوێندراو',
    new_message: 'نامەی نوێ',
    delete_message: 'سڕینەوەی نامە',
    delete_message_confirm: 'دڵنیایت لە سڕینەوەی ئەم نامەیە؟',
    cancel: 'هەڵوەشاندنەوە',
    delete: 'سڕینەوە',
    error: 'هەڵە',
    failed_load_inbox: 'نەتوانرا نامەکان بهێندرێن',
    failed_delete_message: 'نەتوانرا نامەکە بسڕدرێتەوە',
    spam_tester_title: 'تاقیکەرەوەی سپام',
    spam_tester_subtitle: 'پێش چالاککردنی فلتەر، کۆمێنتەکە تاقی بکەرەوە',
    comment_text: 'دەقی کۆمێنت',
    write_comment: 'کۆمێنتێک بنووسە...',
    test: 'تاقیکردنەوە',
    text_required: 'دەق پێویستە',
    enter_comment_first: 'تکایە سەرەتا کۆمێنتێک بنووسە.',
    spam_test_failed: 'تاقیکردنەوەی سپام شکستی هێنا',
    spam: 'سپام',
    safe: 'ئاسایی',
    confidence: 'باوەڕپێکراوی',
    detected_keywords: 'وشەی دۆزراوە',
    none: 'هیچ',
    login_failed: 'چوونەژوورەوە سەرکەوتوو نەبوو',
    dashboard_open_failed: 'کردنەوەی داشبۆرد سەرکەوتوو نەبوو',
    unknown_error: 'هەڵەی نەناسراو',
    please_wait: 'تکایە چاوەڕێ بکە...',
    continue: 'بەردەوامبە',
    network_error_try_again: 'هەڵەی نێتۆرک. تکایە دووبارە هەوڵبدە.',
    api_not_configured: 'API URL ڕێکنەخراوە.',
    status: 'دۆخ',
    expiry: 'بەسەرچوون',
    role: 'ڕۆڵ',
    active: 'چالاک',
    inactive: 'ناچالاک',
    admin: 'ئەدمین',
    user: 'بەکارهێنەر',
    log_out: 'چوونەدەرەوە',
    log_out_confirm: 'دڵنیایت؟',
    loading: 'چاوەڕێ...',
    delete_account: 'سڕینەوەی هەژمار',
    delete_account_title: 'سڕینەوەی هەژمار',
    delete_account_confirm: 'ئەمە هەژمارەکەت ناچالاک دەکات.',
    deleting: 'سڕدرێتەوە...',
    select_page: 'پەیج هەڵبژێرە',
    page_id: 'ناسنامەی پەیج',
    likes: 'لایک',
    followers: 'فۆڵۆوەر',
    replies: 'وەڵام',
    stats_load_failed: 'نەتوانرا ئامار بهێندرێت',
    stats_fetch_error: 'هەڵە لە هێنانی ئامار',
    pages_load_failed: 'نەتوانرا پەیجەکان بهێندرێن',
    selected_page: 'پەیجی هەڵبژێردراو',
    change_page_hint: 'بۆ گۆڕینی پەیج، لەسەر ناوی پەیجەکەی سەرەوە دابگرە.',
    no_pages_found: 'هیچ پەیجێک نەدۆزرایەوە.',
    no_pages_available: 'هیچ پەیجێک نییە.',
    no_connected_pages: 'هیچ پەیجێکی بەستراو نەدۆزرایەوە.',
    blocked_page_message: 'ئەم پەیجە ڕێگری لێکراوە و ناتوانرێت بەکاربهێنرێت.',
    restriction_reason_label: 'هۆکاری ڕێگری',
    restriction_reason_empty: 'هۆکارێک دیاری نەکراوە.',
    blocked_account_message: 'هەژمارەکەت ئێستا ڕێگری لێکراوە یان ناچالاکە.',
    select_page_first_for_posts: 'تکایە سەرەتا پەیجێک هەڵبژێرە بۆ بینینی ڕێکخستنەکان.',
    active_post: 'پۆستی چالاک',
    active_posts_only: 'پۆستی چالاک کراو',
    all_posts: 'هەموو پۆستەکان',
    no_active_posts_found: 'هیچ پۆستێکی چالاک بۆ ئەم پەیجە نەدۆزرایەوە.',
    inactive_post: 'چالاک نییە',
    post_info: 'زانیاری پۆست',
    read_more: 'زیاتر بخوێنەوە',
    show_less: 'کەمتر پیشان بدە',
    date: 'بەروار',
    set_auto_reply: 'وەڵامی ئۆتۆماتیک دابنێ',
    post_not_configured: 'ئەم پۆستە ڕێکخستن نییە، بە دوگمەکە دروستی بکە.',
    load_more: 'زیاتر ببینە',
    refreshing_text: 'باردەکرێت...',
    refresh: 'نوێکردنەوە',
    select_platform_page: 'هەژمار/پەیج بۆ ئەم پلاتفۆرمە هەڵبژێرە',
    select_instagram_id: 'هەڵبژاردنی ئەم Instagram ID',
    select_page_id: 'هەڵبژاردنی ئەم Page ID',
    auto_reply_settings: 'ڕێکخستنی وەڵامی ئۆتۆماتیک',
    comment_reply_message: 'وەڵامی کۆمێنت',
    quick_comment_replies: 'وەڵامی دڵخواز',
    quick_reply_1: 'سوپاس بۆ کۆمێنتەکەت',
    quick_reply_2: 'تکایە نامەی تایبەت بنێرە بۆمان',
    quick_reply_3: 'زانیاری زیاتر لە ئینبۆکسەکەت هەیە',
    quick_reply_4: 'تیمی ئێمە بەم زووانە پەیوەندیت پێوە دەکات',
    quick_reply_5: 'سوپاس بۆ پشتگیریت',
    quick_reply_tokens: 'Placeholderەکان',
    quick_reply_help_short: 'تێبینی: placeholder وەک {comment}، {user_first_name}، {page_name}، {post_id} بەکاربهێنە.',
    quick_reply_custom_placeholder: 'وەڵامی دڵخوازی خۆت بنووسە...',
    quick_reply_add_hint: 'بۆ زیادکردنی وەڵامی دڵخوازی خۆت، لە + بدە',
    pm_reply_message: 'وەڵامی نامە',
    messenger_media: 'میدیای مەسنجەر',
    media_types: 'وێنە، ڤیدیۆ، دەنگ، دوگمە',
    open: 'کردنەوە',
    close: 'داخستن',
    image: 'وێنە',
    video: 'ڤیدیۆ',
    audio: 'دەنگ',
    no_image: 'هیچ وێنەیەک نییە',
    no_video: 'هیچ ڤیدیۆیەک نییە',
    no_audio: 'هیچ دەنگێک نییە',
    upload: 'Upload',
    record: 'Record',
    stop_and_save: 'Stop & Save',
    delete_item: 'سڕینەوە',
    buttons_messenger: 'دوگمەی Messenger',
    add_button: 'زیادکردنی دوگمە',
    button_suggestions: 'دوگمەی پێشنیارکراو',
    edit: 'دەسکاریکردن',
    save_edit: 'پاشەکەوتی دەسکاری',
    save: 'پاشەکەوتکردن',
    saving: 'پاشەکەوت دەکرێت...',
    no_buttons_yet: 'هێشتا هیچ دوگمەیەک دانەنراوە',
    button_name_placeholder: 'ناوی دوگمە',
    whatsapp_phone_placeholder: 'ژمارەی واتساپ 964 xxxx xxx xxx',
    whatsapp_text_placeholder: 'دەقی ئامادەی واتساپ',
    button_link_placeholder: 'لینکی دوگمە (https://...)',
    enter_page_id: 'Page ID بنووسە',
    enter_instagram_id: 'Instagram ID بنووسە',
    upload_progress: 'ڕێژەی ئەپلۆد',
    loading_preview_audio: 'بارکردنی previewی دەنگ...',
    cant_show_video_preview: 'نەتوانرا previewی ڤیدیۆ پیشان بدرێت.',
    cant_play_audio: 'نەتوانرا دەنگەکە پلەی بکرێت.',
    warning: 'ئاگاداری',
    only_images_limit: 'تەنها {count} وێنە دەتوانیت زیاد بکەیت.',
    gallery_permission_required: 'ڕێگەی Gallery پێویستە.',
    unsupported_audio_format: 'فۆرماتی دەنگ پشتیوانی ناکرێت. تکایە mp3/m4a/wav بەکاربهێنە.',
    upload_failed: 'نەتوانرا ئەپلۆد پاشەکەوت بکرێت.',
    mic_permission_required: 'ڕێگای مایکڕۆفۆن پێویستە.',
    min_recording_warning: 'تکایە لانیکەم 1 چرکە ڕیکۆرد بکە، پاشان وەستێنە.',
    button_name_required: 'تکایە ناوی دوگمە بنووسە.',
    whatsapp_phone_invalid: 'تکایە ژمارەی واتساپی دروست بنووسە.',
    invalid_link: 'تکایە لینکێکی دروست بنووسە.',
    max_buttons_reached: 'تەنها {count} دوگمە دەتوانیت زیاد بکەیت.',
    messenger_chat_flow_title: 'چات فلۆوی مەسنجەر',
    messenger_chat_flow_sub: 'دانانی دوگمە و وەڵامی ئۆتۆماتیک',
    page_selection: 'هەڵبژاردنی پەیج',
    welcome_message: 'نامەی بەخێرهاتن',
    welcome_placeholder: 'دەقی بەخێرهاتن بۆ سەرەتای چات',
    preview: 'پێشبینین',
    button_name: 'ناوی دوگمە',
    button_reply: 'وەڵامی دوگمە',
    add_button_label: 'زیادکردنی دوگمە',
    limit: 'سنوور',
    link_step_to_main: 'بەستنی هەنگاو بە هەنگاو بە دوگمەی سەرەکی',
    main_button_name: 'ناوی دوگمەی سەرەکی',
    add_sub_button: 'زیادکردنی دوگمەی لاوەکی',
    sub_button_name: 'ناوی دوگمەی لاوەکی',
    sub_button_reply: 'وەڵامی دوگمەی لاوەکی',
    save_chat_flow: 'پاشەکەوتی چات فلۆو',
    back: 'گەڕانەوە',
    no_text: '...',
    help_about_app: 'دەربارەی ئەپ',
    help_auto_reply: 'چۆن Auto Reply دابنێم؟',
    help_chat_flow: 'چۆن Chat Flow ڕێک بخەم؟',
    live_chat_whatsapp: 'لایڤ چات واتساپ',
    website_label: 'وێبسایت',
    about_label: 'دەربارە',
    live_chat: 'لایڤ چات',
    walam_team: 'تیمی Walam',
    active_now: 'ئێستا چالاکە',
    no_messages: 'هیچ نامەیەک نییە.',
    send: 'ناردن',
    write_message: 'نامە بنووسە...',
    you: 'تۆ',
    plan_monthly_price: '6.99$ / مانگ',
    plan_quarterly_price: '17.97$ / 3 مانگ',
    plan_yearly_price: '59.88$ / ساڵ',
    plan_basic: 'بنەڕەتی',
    plan_popular: 'زۆر بەکارهاتوو',
    plan_best_value: 'باشترین نرخ',
    plan_start_now: 'ئێستا دەستپێبکە',
    plan_save_more: 'لە پلانی 3 مانگ پارە پاشەکەوت بکە',
    plan_full_access: 'دەستگەیشتنێکی تەواو بۆ 1 ساڵ',
    plan_monthly_feature_1: 'وەڵامی ئۆتۆماتیک بۆ فەیسبووک و ئینستاگرام',
    plan_monthly_feature_2: 'دوگمەی مەسنجەر و ئامرازی میدیا',
    plan_monthly_feature_3: 'لایڤ چات و تایبەتمەندی بانگێشت',
    plan_quarterly_feature_1: 'هەموو تایبەتمەندیەکانی پلانی مانگانە',
    plan_quarterly_feature_2: 'نرخی باشتر بۆ بەکارهێنانی 3 مانگ',
    plan_quarterly_feature_3: 'جێگیری و نوێکاری بە خێرایی',
    plan_yearly_feature_1: 'هەموو تایبەتمەندیەکانی پلانی سێ مانگ',
    plan_yearly_feature_2: 'باشترین نرخی ساڵانە',
    plan_yearly_feature_3: 'گەشەی درێژخایەن بەبێ وەستان',
    referral_code_title: 'کۆدی بانگێشت',
    referral_wallet_title: 'جزدانى بانگێشت',
    referral_loading: 'بارکردن...',
    referral_balance: 'باڵانس',
    referral_pending_reward: 'پاداشتی چاوەڕوان',
    referral_earned: 'قازانج',
    referral_used: 'بەکارهاتوو',
    referral_pending_users: 'بەکارهێنەری چاوەڕوان',
    referral_approved_users: 'بەکارهێنەری پەسەندکراو',
    referral_used_code: 'کۆدی بەکارهاتوو',
    referral_my_code: 'کۆدی من',
    referral_use_code: 'کۆدی بانگێشت داخڵ بکە',
    referral_copy_hint: 'لە خانەی کۆدەکە دابگرە و کۆپی بکە.',
    referral_code_required: 'کۆدی بانگێشت پێویستە.',
    referral_code_applied: 'کۆدی بانگێشت جێبەجێکرا.',
    referral_code_copied: 'کۆدی بانگێشت کۆپی کرا.',
    referral_api_not_updated: 'API ی سێرڤەر هێشتا نوێنەکراوەتەوە. تکایە نوێترین mobile-api.php بنێرە سێرڤەر.',
    apply: 'جێبەجێ بکە',
    used: 'بەکارهاتوو',
    copy_code: 'کۆدی کۆپی بکە',
    help_about_line_1: 'ئەم ئەپە بۆ ئۆتۆماتیککردنی وەڵامەکانە لە Facebook و Instagram.',
    help_about_line_2: 'سودی سەرەکی: خێرایی وەڵامدانەوە، کەمکردنەوەی کات، و ڕێکخستنی گفتوگۆ.',
    help_auto_1: '1) لە بەشی Posts پەیج هەڵبژێرە.',
    help_auto_2: '2) بۆ هەر پۆستێک وەڵامی Comment یان PM بنوسە.',
    help_auto_3: '3) ئەگەر پێویست بوو میدیا (وێنە/ڤیدیۆ/دەنگ) زیاد بکە.',
    help_auto_4: '4) دوای گۆڕانکاری هەمیشە پاشەکەوت بکە.',
    help_flow_1: '1) لە Chat Flow پەیجێک هەڵبژێرە.',
    help_flow_2: '2) دوگمەی سەرەکی دروست بکە (وەک: نرخ، پەیوەندی، فێرکاری).',
    help_flow_3: '3) بۆ هەر دوگمەیەک دەقی وەڵام دابنێ.',
    help_flow_4: '4) لە هەنگاو بە هەنگاو دوگمەی لاوەکی زیاد بکە بۆ ڕێکخستنی زیاتر.',
    help_flow_5: '5) پێشبینین بکە و دواتر پاشەکەوت بکە.',
  },
  ar: {
    app_name: 'Walam',
    intro_subtitle: 'إدارة الصفحات وأتمتة الردود من الهاتف',
    use_cases: 'الاستخدام',
    pricing: 'الأسعار',
    whatsapp: 'واتساب',
    website: 'الموقع',
    platform: 'المنصات',
    login_facebook: 'تسجيل الدخول بفيسبوك',
    enter_app: 'دخول',
    language: 'اللغة',
    home: 'الرئيسية',
    inbox: 'الرسائل',
    stats: 'الإحصائيات',
    posts: 'المنشورات',
    chat_flow: 'تدفق الدردشة',
    settings: 'الإعدادات',
    dashboard: 'لوحة التحكم',
    overview: 'نظرة عامة',
    account_time: 'وقت الحساب',
    no_expiry_date: 'لا يوجد تاريخ انتهاء',
    time_left_suffix: 'متبقي',
    time_passed_suffix: 'منذ',
    could_not_load_dashboard_data: 'تعذر تحميل بيانات لوحة التحكم',
    active_posts: 'المنشورات النشطة',
    today_replies: 'ردود اليوم',
    total_replies: 'إجمالي الردود',
    refresh_data: 'تحديث البيانات',
    account_support: 'الحساب والدعم',
    help: 'المساعدة',
    buy_plan: 'شراء خطة',
    page_stats_title: 'الصفحات',
    page_stats_subtitle: 'إحصائيات الصفحة المحددة',
    posts_manage_title: 'المنشورات',
    posts_manage_subtitle: 'المنشورات النشطة حسب الصفحة المحددة',
    chat_flow_subtitle: 'إعداد تدفق دردشة ماسنجر',
    total_pages: 'إجمالي الصفحات',
    active_pages: 'الصفحات النشطة',
    page_stats: 'إحصائيات الصفحة',
    chart_last_30_days: 'مخطط آخر 30 يوم',
    total: 'الإجمالي',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    chat_preview: 'معاينة الدردشة',
    button_setup: 'إعداد الأزرار',
    step_by_step_buttons: 'أزرار خطوة بخطوة',
    inbox_title: 'الرسائل',
    inbox_subtitle: 'الرسائل المهمة من الإدارة',
    no_messages_yet: 'لا توجد رسائل بعد.',
    unread_messages: 'رسائل غير مقروءة',
    unread_message: 'رسالة غير مقروءة',
    new_message: 'رسالة جديدة',
    delete_message: 'حذف الرسالة',
    delete_message_confirm: 'هل أنت متأكد من حذف هذه الرسالة؟',
    cancel: 'إلغاء',
    delete: 'حذف',
    error: 'خطأ',
    failed_load_inbox: 'تعذر تحميل الرسائل',
    failed_delete_message: 'تعذر حذف الرسالة',
    spam_tester_title: 'فاحص السبام',
    spam_tester_subtitle: 'اختبر التعليق قبل تفعيل الفلتر',
    comment_text: 'نص التعليق',
    write_comment: 'اكتب تعليقًا...',
    test: 'اختبار',
    text_required: 'النص مطلوب',
    enter_comment_first: 'يرجى إدخال تعليق أولاً.',
    spam_test_failed: 'تعذر إجراء اختبار السبام',
    spam: 'سبام',
    safe: 'آمن',
    confidence: 'الثقة',
    detected_keywords: 'الكلمات المكتشفة',
    none: 'لا يوجد',
    login_failed: 'فشل تسجيل الدخول',
    dashboard_open_failed: 'فشل فتح لوحة التحكم',
    unknown_error: 'خطأ غير معروف',
    please_wait: 'يرجى الانتظار...',
    continue: 'متابعة',
    network_error_try_again: 'خطأ في الشبكة. حاول مرة أخرى.',
    api_not_configured: 'لم يتم إعداد رابط API.',
    status: 'الحالة',
    expiry: 'الانتهاء',
    role: 'الدور',
    active: 'نشط',
    inactive: 'غير نشط',
    admin: 'مدير',
    user: 'مستخدم',
    log_out: 'تسجيل الخروج',
    log_out_confirm: 'هل أنت متأكد؟',
    loading: 'جاري التحميل...',
    delete_account: 'حذف الحساب',
    delete_account_title: 'حذف الحساب',
    delete_account_confirm: 'سيتم تعطيل هذا الحساب.',
    deleting: 'جارٍ الحذف...',
    select_page: 'اختر الصفحة',
    page_id: 'معرف الصفحة',
    likes: 'إعجابات',
    followers: 'متابعون',
    replies: 'ردود',
    stats_load_failed: 'تعذر تحميل الإحصائيات',
    stats_fetch_error: 'خطأ أثناء جلب الإحصائيات',
    pages_load_failed: 'تعذر تحميل الصفحات',
    selected_page: 'الصفحة المحددة',
    change_page_hint: 'اضغط اسم الصفحة فوق لتغييرها.',
    no_pages_found: 'لم يتم العثور على أي صفحة.',
    no_pages_available: 'لا توجد صفحات.',
    no_connected_pages: 'لم يتم العثور على صفحات مرتبطة.',
    blocked_page_message: 'هذه الصفحة محظورة ولا يمكن استخدامها.',
    restriction_reason_label: 'سبب الحظر',
    restriction_reason_empty: 'لم يتم تحديد سبب.',
    blocked_account_message: 'حسابك مقيد أو غير نشط حالياً.',
    select_page_first_for_posts: 'يرجى اختيار صفحة أولاً لعرض الإعدادات.',
    active_post: 'منشور نشط',
    active_posts_only: 'المنشورات النشطة',
    all_posts: 'كل المنشورات',
    no_active_posts_found: 'لا توجد منشورات نشطة لهذه الصفحة.',
    inactive_post: 'غير نشط',
    post_info: 'معلومات المنشور',
    read_more: 'اقرأ المزيد',
    show_less: 'عرض أقل',
    date: 'التاريخ',
    set_auto_reply: 'إعداد الرد التلقائي',
    post_not_configured: 'هذا المنشور غير مُعد بعد. أنشئه عبر الزر.',
    load_more: 'عرض المزيد',
    refreshing_text: 'جارٍ التحميل...',
    refresh: 'تحديث',
    select_platform_page: 'اختر حساب/صفحة لهذه المنصة',
    select_instagram_id: 'اختيار Instagram ID هذا',
    select_page_id: 'اختيار Page ID هذا',
    auto_reply_settings: 'إعدادات الرد التلقائي',
    comment_reply_message: 'رسالة رد التعليق',
    quick_comment_replies: 'ردود سريعة',
    quick_reply_1: 'شكراً على تعليقك',
    quick_reply_2: 'يرجى إرسال رسالة خاصة لنا',
    quick_reply_3: 'المزيد من التفاصيل موجود في الرسائل',
    quick_reply_4: 'فريقنا سيتواصل معك قريباً',
    quick_reply_5: 'شكراً لدعمك',
    quick_reply_tokens: 'Placeholderات',
    quick_reply_help_short: 'ملاحظة: استخدم Placeholder مثل {comment} و {user_first_name} و {page_name} و {post_id}.',
    quick_reply_custom_placeholder: 'اكتب الرد السريع الخاص بك...',
    quick_reply_add_hint: 'اضغط + لإضافة ردك المفضل الخاص بك',
    pm_reply_message: 'رسالة الخاص',
    messenger_media: 'وسائط ماسنجر',
    media_types: 'صورة، فيديو، صوت، أزرار',
    open: 'فتح',
    close: 'إغلاق',
    image: 'صورة',
    video: 'فيديو',
    audio: 'صوت',
    no_image: 'لا توجد صورة',
    no_video: 'لا يوجد فيديو',
    no_audio: 'لا يوجد صوت',
    upload: 'رفع',
    record: 'تسجيل',
    stop_and_save: 'إيقاف وحفظ',
    delete_item: 'حذف',
    buttons_messenger: 'أزرار ماسنجر',
    add_button: 'إضافة زر',
    button_suggestions: 'أزرار مقترحة',
    edit: 'تعديل',
    save_edit: 'حفظ التعديل',
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    no_buttons_yet: 'لا توجد أزرار بعد',
    button_name_placeholder: 'اسم الزر',
    whatsapp_phone_placeholder: 'رقم واتساب 964 xxxx xxx xxx',
    whatsapp_text_placeholder: 'نص واتساب الجاهز',
    button_link_placeholder: 'رابط الزر (https://...)',
    enter_page_id: 'اكتب Page ID',
    enter_instagram_id: 'اكتب Instagram ID',
    upload_progress: 'نسبة الرفع',
    loading_preview_audio: 'جارٍ تحميل معاينة الصوت...',
    cant_show_video_preview: 'لا يمكن عرض معاينة الفيديو.',
    cant_play_audio: 'لا يمكن تشغيل معاينة الصوت.',
    warning: 'تنبيه',
    only_images_limit: 'يمكنك رفع {count} صورة فقط.',
    gallery_permission_required: 'مطلوب إذن المعرض.',
    unsupported_audio_format: 'صيغة الصوت غير مدعومة. استخدم mp3/m4a/wav.',
    upload_failed: 'فشل الرفع.',
    mic_permission_required: 'مطلوب إذن الميكروفون.',
    min_recording_warning: 'يرجى التسجيل لمدة ثانية واحدة على الأقل.',
    button_name_required: 'يرجى إدخال اسم الزر.',
    whatsapp_phone_invalid: 'يرجى إدخال رقم واتساب صحيح.',
    invalid_link: 'يرجى إدخال رابط صحيح.',
    max_buttons_reached: 'تم الوصول للحد: {count} أزرار فقط.',
    messenger_chat_flow_title: 'تدفق دردشة ماسنجر',
    messenger_chat_flow_sub: 'إعداد الأزرار والردود التلقائية',
    page_selection: 'اختيار الصفحة',
    welcome_message: 'رسالة الترحيب',
    welcome_placeholder: 'نص الترحيب لأول دردشة',
    preview: 'معاينة',
    button_name: 'اسم الزر',
    button_reply: 'رد الزر',
    add_button_label: 'إضافة زر',
    limit: 'الحد',
    link_step_to_main: 'ربط خطوة بخطوة بالزر الرئيسي',
    main_button_name: 'اسم الزر الرئيسي',
    add_sub_button: 'إضافة زر فرعي',
    sub_button_name: 'اسم الزر الفرعي',
    sub_button_reply: 'رد الزر الفرعي',
    save_chat_flow: 'حفظ تدفق الدردشة',
    back: 'رجوع',
    no_text: '...',
    help_about_app: 'حول التطبيق',
    help_auto_reply: 'كيف أضبط الرد التلقائي؟',
    help_chat_flow: 'كيف أضبط Chat Flow؟',
    live_chat_whatsapp: 'لايف شات واتساب',
    website_label: 'الموقع',
    about_label: 'حول',
    live_chat: 'لايف شات',
    walam_team: 'فريق Walam',
    active_now: 'نشط الآن',
    no_messages: 'لا توجد رسائل.',
    send: 'إرسال',
    write_message: 'اكتب رسالة...',
    you: 'أنت',
    plan_monthly_price: '6.99$ / شهر',
    plan_quarterly_price: '17.97$ / 3 أشهر',
    plan_yearly_price: '59.88$ / سنة',
    plan_basic: 'أساسي',
    plan_popular: 'الأكثر طلباً',
    plan_best_value: 'أفضل قيمة',
    plan_start_now: 'ابدأ الآن',
    plan_save_more: 'وفّر أكثر مع خطة 3 أشهر',
    plan_full_access: 'وصول كامل لمدة سنة',
    plan_monthly_feature_1: 'ردود تلقائية لفيسبوك وإنستغرام',
    plan_monthly_feature_2: 'أزرار ماسنجر وأدوات الوسائط',
    plan_monthly_feature_3: 'دردشة مباشرة وميزات الإحالة',
    plan_quarterly_feature_1: 'كل ميزات الخطة الشهرية',
    plan_quarterly_feature_2: 'قيمة أفضل لمدة 3 أشهر',
    plan_quarterly_feature_3: 'استقرار وتحديثات بأولوية',
    plan_yearly_feature_1: 'كل ميزات الخطة ربع السنوية',
    plan_yearly_feature_2: 'أفضل سعر سنوي',
    plan_yearly_feature_3: 'نمو طويل المدى بدون انقطاع',
    referral_code_title: 'كود الدعوة',
    referral_wallet_title: 'محفظة الدعوة',
    referral_loading: 'جاري التحميل...',
    referral_balance: 'الرصيد',
    referral_pending_reward: 'مكافأة قيد الانتظار',
    referral_earned: 'المكتسب',
    referral_used: 'المستخدم',
    referral_pending_users: 'المستخدمون قيد الانتظار',
    referral_approved_users: 'المستخدمون الموافق عليهم',
    referral_used_code: 'الكود المستخدم',
    referral_my_code: 'كودي',
    referral_use_code: 'استخدم كود دعوة',
    referral_copy_hint: 'اضغط على خانة الكود ثم انسخه.',
    referral_code_required: 'كود الدعوة مطلوب.',
    referral_code_applied: 'تم تطبيق كود الدعوة.',
    referral_code_copied: 'تم نسخ كود الدعوة.',
    referral_api_not_updated: 'واجهة API في الخادم غير محدّثة بعد. يرجى رفع أحدث ملف mobile-api.php.',
    apply: 'تطبيق',
    used: 'مستخدم',
    copy_code: 'نسخ الكود',
    help_about_line_1: 'هذا التطبيق لأتمتة الردود على Facebook وInstagram.',
    help_about_line_2: 'الفائدة الأساسية: سرعة الرد، تقليل الوقت، وتنظيم المحادثات.',
    help_auto_1: '1) في Posts اختر صفحتك.',
    help_auto_2: '2) لكل منشور اكتب رد Comment أو PM.',
    help_auto_3: '3) أضف وسائط عند الحاجة (صورة/فيديو/صوت).',
    help_auto_4: '4) احفظ دائمًا بعد التعديل.',
    help_flow_1: '1) في Chat Flow اختر صفحة.',
    help_flow_2: '2) أنشئ أزرارًا رئيسية (الأسعار، التواصل، الشروحات).',
    help_flow_3: '3) ضع نص رد لكل زر.',
    help_flow_4: '4) أضف أزرارًا فرعية خطوة بخطوة.',
    help_flow_5: '5) اعمل معاينة ثم احفظ.',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<AppLang>('en');

  useEffect(() => {
    AsyncStorage.getItem('walam.lang')
      .then((v) => {
        if (v === 'ku' || v === 'en' || v === 'ar') setLangState(v);
      })
      .catch(() => {});
  }, []);

  async function setLang(next: AppLang) {
    setLangState(next);
    await AsyncStorage.setItem('walam.lang', next);
  }

  const value = useMemo<LanguageContextValue>(
    () => ({
      lang,
      isRTL: lang === 'ku' || lang === 'ar',
      setLang,
      t: (key: string) => translations[lang][key] || translations.en[key] || key,
    }),
    [lang]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
